import NavigationDesktop from "@/components/Navigation/NavigationDesktop";
import { CartContextProvider } from "./api/cartContext";
import "./globals.css";
import Script from "next/script";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <CartContextProvider>
      <html lang="en">
        <head>
          <Script
            crossOrigin="anonymous"
            src="https://kit.fontawesome.com/f141ac3909.js"
          />
        </head>
        <body className="4xl:container mx-auto">
          <NavigationDesktop />
          {children}
        </body>
      </html>
    </CartContextProvider>
  );
}
